pool:
  name: 'SelfHostedPool'  

stages:
  - stage: Build
    jobs:
      - job: BuildBackend
        steps:
          - script: |
              export JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64
              export PATH=$JAVA_HOME/bin:$PATH
              java -version
            displayName: 'Set up Java 21'

          - script: |
              mvn clean test
            displayName: 'Run Unit Tests'

          - script: |
              mvn clean package -DskipTests
            displayName: 'Build JAR file'

          - task: PublishBuildArtifacts@1
            displayName: 'Publish JAR Artifact'
            inputs:
              pathToPublish: 'target/Employee_Management_System-0.0.1-SNAPSHOT.jar'
              artifactName: 'drop'

  - stage: Deploy
    jobs:
      - job: DeployBackend
        steps:
          - script: |
              sudo pkill -f 'Employee_Management_System' || true
              nohup java -jar /home/Aditya/myagent/_work/2/s/target/Employee_Management_System-0.0.1-SNAPSHOT.jar > ~/springboot-app/app.log 2>&1 &
            displayName: 'Restart Backend Service'
