pool:
  name: 'SelfHostedPool'  # Name of the pool you created

stages:
  - stage: Build
    jobs:
      - job: BuildBackend
        steps:
          - task: JavaToolInstaller@0
            inputs:
              versionSpec: '21'
              jdkArchitecture: 'x64'
              jdkSource: 'PreInstalled'
          - script: |
              mvn clean package
            displayName: 'Build JAR file'
