pool:
  name: 'SelfHostedPool'  # Name of the pool you created

stages:
  - stage: Build
    jobs:
      - job: BuildBackend
        steps:
          - script: |
              export JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64
              export PATH=$JAVA_HOME/bin:$PATH
              java -version
              mvn clean package
            displayName: 'Build JAR file'
