pool:
  name: 'SelfHostedPool'  # Name of the pool you created

stages:
  - stage: Build
    jobs:
      - job: BuildBackend
        steps:
          # Install Java if not already installed on the agent
          - task: JavaToolInstaller@0
            inputs:
              versionSpec: '21'       # Desired Java version
              jdkArchitectureOption: 'x64'  # Correct parameter to specify architecture
              jdkSource: 'PreInstalled'  # Use preinstalled JDK on the agent

          # Use Maven to build the JAR file
          - script: |
              mvn clean package
            displayName: 'Build JAR file'
