trigger:
  branches:
    include:
      - main  # Runs the pipeline when changes are pushed to main branch

stages:
- stage: Build
  displayName: 'Build Stage'
  jobs:
  
  # Backend Build Job
  - job: BuildBackend
    displayName: 'Build Spring Boot Backend'
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - checkout: self

    - task: UseJavaVersion@0
      inputs:
        version: '21'  # Java version for backend
        architecture: 'x64'

    - script: |
        chmod +x mvnw
        ./mvnw clean package -DskipTests
      displayName: 'Build Spring Boot Application'

    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: 'target/*.jar'
        artifactName: 'backend-artifact'

  # Frontend Build Job
  - job: BuildFrontend
    displayName: 'Build React Frontend'
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - checkout: self

    - task: NodeTool@0
      inputs:
        versionSpec: '20.x'

    - script: |
        cd frontend
        npm install
        npm run build
      displayName: 'Build React Application'

    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: 'frontend/build/'
        artifactName: 'frontend-artifact'

- stage: Deploy
  displayName: 'Deploy Stage'
  dependsOn: Build
  jobs:

  # Deploy Backend
  - job: DeployBackend
    displayName: 'Deploy Spring Boot to Azure App Service'
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - task: DownloadBuildArtifacts@0
      inputs:
        artifactName: 'backend-artifact'
        downloadPath: $(Build.ArtifactStagingDirectory)

    - task: AzureWebApp@1
      inputs:
        azureSubscription: 'Azure-Connection-EMS'  # Replace with your service connection name
        appName: 'ems-backend-app'                # Replace with your Azure App Service name
        package: '$(Build.ArtifactStagingDirectory)/*.jar'

  # Deploy Frontend
  - job: DeployFrontend
    displayName: 'Deploy React to Azure Static Web Apps'
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - task: DownloadBuildArtifacts@0
      inputs:
        artifactName: 'frontend-artifact'
        downloadPath: $(Build.ArtifactStagingDirectory)

    - task: AzureStaticWebApp@0
      inputs:
        azureSubscription: 'Azure-Connection-EMS'  
        appName: 'ems-frontend'                    
        package: '$(Build.ArtifactStagingDirectory)'
