name: Backend CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build Spring Boot Application
        run: |
          cd backend
          ./mvnw clean package -DskipTests

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: backend-jar
          path: backend/target/*.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: backend-jar
          path: backend/target

      - name: Deploy JAR to VM
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          VM_USER: ubuntu
          VM_HOST: <your-vm-ip>
          JAR_NAME: employee-management-system.jar
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key && chmod 600 private_key
          scp -i private_key -o StrictHostKeyChecking=no backend/target/*.jar $VM_USER@$VM_HOST:/home/$VM_USER/$JAR_NAME
          ssh -i private_key -o StrictHostKeyChecking=no $VM_USER@$VM_HOST << 'EOF'
            pkill -f $JAR_NAME || true
            nohup java -jar /home/$VM_USER/$JAR_NAME > /dev/null 2>&1 &
          EOF
          rm -f private_key
