name: Deploy Spring Boot Backend

on:
  push:
    branches:
      - main  # Runs the workflow on pushes to 'main' branch
  workflow_dispatch:  # Allows manual execution

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build JAR file
        run: |
          cd backend
          ./mvnw clean install

      - name: Copy JAR to Deployment Directory
        run: |
          mkdir -p /home/azureuser/app
          cp backend/target/*.jar /home/azureuser/app/app.jar

      - name: Restart Application
        run: |
          echo "Stopping existing Spring Boot application..."
          pkill -f 'java -jar /home/azureuser/app/app.jar' || true
          echo "Starting new version..."
          nohup java -jar /home/azureuser/app/app.jar > /home/azureuser/app/app.log 2>&1 &
