trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UseJavaVersion@1
    inputs:
      versionSpec: '21'
      jdkArchitecture: 'x64'

  - script: |
      cd backend
      ./mvnw clean install
    displayName: 'Build Backend with Maven'

  - script: |
      mkdir -p /home/azureuser/app
      cp backend/target/*.jar /home/azureuser/app/app.jar
    displayName: 'Copy JAR to Deployment Directory'

  - script: |
      echo "Stopping existing Spring Boot application..."
      pkill -f 'java -jar /home/azureuser/app/app.jar' || true
      echo "Starting new version..."
      nohup java -jar /home/azureuser/app/app.jar > /home/azureuser/app/app.log 2>&1 &
    displayName: 'Restart Application'
